import datetime
i=datetime.datetime.now()
print ("%s"%i)
print("%s"%i.isoformat())
print("%s"%i.year)
print("%s"%i.month)
print("%s"%i.day)
print("%s %s %s"%(i.day,i.month,i.year))
print("%s"%i.hour)
print("%s"%i.minute)
print("%s"%i.second)